### ISSUE TITLE
clatd on single interface?

### ISSUE THREAD

**Issue by vwidmer** [toreanderson/clatd#27]
How to run clatd on a single interface?  with out detecting other connections?

**Comment by toreanderson** [comment]
I don't understand these question. Clatd should work fine on machines with a single interface, and it does not at all «detect connections» (whatever that means).

**Comment by vwidmer** [comment]
sorry, I will explain better.

If I have 2 wan interfaces

wwan1 = ipv4 connection via ISP 1
wwan2 = ipv6 connection via ISP 2

if I disable wwan1 clatd works fine however if wwan1 is connected before wwan2 or after, then clatd goes down. 

So my question is there a way to run clatd to only check on a single interface and bring up the clat interface even with as in my example, another connection running?

**Comment by toreanderson** [comment]
By default, clatd will not do anything on a system with IPv4 connectivity (see the `v4-conncheck-*` configuration options). You can disable with by adding `v4-conncheck-enable=false` to `/etc/clatd.conf`.

Also, by default, clatd will be restarted whenever interfaces come up or down in order to discover any changes to the network routing, this is done by the NetworkManager dispatcher scripts. They can be removed if you don't like that.

Does that answer your question?
