### ISSUE TITLE
Not able to ping IP literals

### ISSUE THREAD

**Issue by zod076** [toreanderson/clatd#43]
I've installed Clatd on a VPS. It had IPv4, so I removed the default gateway, disabled firewall and started clatd. Then tried pinging 1.1.1.1 and it would just hang there..no replies..

What could be causing this ?

The NAT64 is on the same machine but in it's own network namespace.

**Comment by toreanderson** [comment]
I need more information to be able to make sense of this. Please send me:

1. Output from starting clatd in debug mode (`clatd -d`)
2. Output from `iptables-save`, `ip6tables-save` and `nft list ruleset` when the problem is in effect
3. Simultaneous packet captures on `clat-dev` and `plat-dev`. For example, `tcpdump -i clat` and `tcpdump -i eth0 net 64:ff9b::/96` - replacing «clat» with your `clat-dev`, «eth0» with your `plat-dev` and «64:ff9b::/96» with your `plat-prefix`.
4. While the packet captures are running, send some test traffic (e.g., `ping 1.1.1.1`).

**Comment by zod076** [comment]
I think I know why it doesn't work. Since I removed the default ipv4 gateway for testing while running clatd + NAT64 on the same machine, packets won't go out as the NAT64 will have no way of communicating with the outside world over IPv4...
